version: '3'
services:
  # react
  reactplaid:
    container_name: reactplaid
    build:
      context: './client'
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
    ports:
      - 3000:3000
    depends_on:
      - flaskapi
  
  # flask api
  flaskapi:
    container_name: flaskapi
    build: 
      context: './api'
      dockerfile: Dockerfile
    volumes:
      - './api:/src'
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1